export const currencies = [
    { code: 'AED', symbol: 'د.إ', name: 'ОАЭ дирхам' },
    { code: 'AUD', symbol: '$', name: 'Австралийский доллар' },
    { code: 'BRL', symbol: 'R$', name: 'Бразильский реал' },
    { code: 'BHD', symbol: 'ب.د', name: 'Бахрейнский динар' },
    { code: 'BDT', symbol: '৳', name: 'Бангладешская така' },
    { code: 'BYN', symbol: 'Br', name: 'Белорусский рубль' },
    { code: 'CAD', symbol: '$', name: 'Канадский доллар' },
    { code: 'CHF', symbol: '₣', name: 'Швейцарский франк' },
    { code: 'CNY', symbol: '¥', name: 'Китайский юань' },
    { code: 'COP', symbol: '$', name: 'Колумбийское песо' },
    { code: 'DKK', symbol: 'kr', name: 'Датская крона' },
    { code: 'EUR', symbol: '€', name: 'Евро' },
    { code: 'GBP', symbol: '£', name: 'Британский фунт' },
    { code: 'HUF', symbol: 'Ft', name: 'Венгерский форинт' },
    { code: 'ILS', symbol: '₪', name: 'Израильский шекель' },
    { code: 'INR', symbol: '₹', name: 'Индийская рупия' },
    { code: 'JPY', symbol: '¥', name: 'Японская иена' },
    { code: 'KZT', symbol: '₸', name: 'Казахстанский тенге' },
    { code: 'KWD', symbol: 'د.ك', name: 'Кувейтский динар' },
    { code: 'LKR', symbol: 'Rs', name: 'Шри-ланкийская рупия' },
    { code: 'MXN', symbol: '$', name: 'Мексиканское песо' },
    { code: 'MYR', symbol: 'RM', name: 'Малайзийский ринггит' },
    { code: 'NGN', symbol: '₦', name: 'Нигерийская наира' },
    { code: 'NOK', symbol: 'kr', name: 'Норвежская крона' },
    { code: 'OMR', symbol: 'ر.ع.', name: 'Оманский риал' },
    { code: 'PKR', symbol: '₨', name: 'Пакистанская рупия' },
    { code: 'PHP', symbol: '₱', name: 'Филиппинское песо' },
    { code: 'PLN', symbol: 'zł', name: 'Польский злотый' },
    { code: 'QAR', symbol: 'ر.ق', name: 'Катарский риал' },
    { code: 'RON', symbol: 'lei', name: 'Румынский лей' },
    { code: 'RUB', symbol: '₽', name: 'Российский рубль' },
    { code: 'SAR', symbol: 'ر.س', name: 'Саудовский риял' },
    { code: 'SEK', symbol: 'kr', name: 'Шведская крона' },
    { code: 'THB', symbol: '฿', name: 'Тайский бат' },
    { code: 'TRY', symbol: '₺', name: 'Турецкая лира' },
    { code: 'USD', symbol: '$', name: 'Американский доллар' },
    { code: 'UZS', symbol: 'сум', name: 'Узбекский сум' },
    { code: 'VND', symbol: '₫', name: 'Вьетнамский донг' },
    { code: 'ZAR', symbol: 'R', name: 'Южноафриканский ранд' },
    { code: 'KRW', symbol: '₩', name: 'Южнокорейская вона' },
  ];
  
  